### ISSUE TITLE
[Bug] doris can not release file handler after drop table with param force 

### ISSUE THREAD

**Issue by pyongj** [apache/doris#24036]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0 Release

### What's Wrong?

when dorp table with param force , the file handler not closed .  the unreleased file handler make disk space not released , which will eventually exhausts the space of disk. 
reference: 
#3944 

### What You Expected?

release the file handler. 

### How to Reproduce?

1. create a table . such as: create table t_a like t_b; 
2. load data into the table . such as : insert into t_a select * from t_b;
3. wait a few minutes. execute command: drop table t_a force; 
4. wait a few minutes. execute command on linux server: lsof -p $BEID | grep 'delete' | grep 'trash' 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pyongj** [comment]
The bug has been fixed in version 2.0.1

**Comment by Damon07** [comment]
we can still see the not released file handlers within path trash in version 2.0.4 @pyongj
