### ISSUE TITLE
[Bug] 用hdfs进行还原时，提示failed to download|signature=323207|job_id=295022|error=[NOT_FOUND]failed to open file for md5sum

### ISSUE THREAD

**Issue by Jinxv1007** [apache/doris#33303]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0跟2.1.1都有这个问题

### What's Wrong?

用hdfs进行还原时，提示failed to download|signature=323207|job_id=295022|error=[NOT_FOUND]failed to open file for md5sum。备份是在2.0.3版本上进行的，要还原到2.1.0版本跟2.1.1版本就会提示这个错误

### What You Expected?

就是能够正常恢复

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mongo360** [comment]
the same problem

**Comment by zh0122** [comment]
same on 2.1.2

**Comment by w41ter** [comment]
@d378971067 Can you provide the BE log and the definition of the repository?

**Comment by d378971067** [comment]
> @d378971067 Can you provide the BE log and the definition of the repository?
hadoop version:3.3.4  apache_hdfs_broker version: doris 2.1.0 extension
be.info
![image](https://github.com/apache/doris/assets/18493427/136f6106-ae3f-497d-9001-c3dfe8cb8365)
apache_hdfs_broker.log
![image](https://github.com/apache/doris/assets/18493427/95747cbf-827f-410d-8e38-6d638a981f4e)
error file path
![image](https://github.com/apache/doris/assets/18493427/d1d817e6-aaa2-4c0e-aba5-f2fb89955206)

**Comment by w41ter** [comment]
This problem has been fixed in version 2.1.3, and the relevant PR is at #33556.

@d378971067 @zh0122 @mongo360

**Comment by d378971067** [comment]
It's probably not fixed yet. This image is a screenshot based on version 2.1.3.
@w41ter 
![image](https://github.com/apache/doris/assets/18493427/524a47d1-6873-475c-8151-1b79038c873b)

**Comment by zh0122** [comment]
> This problem has been fixed in version 2.1.3, and the relevant PR is at #33556.
> 
> @d378971067 @zh0122 @mongo360

![image](https://github.com/apache/doris/assets/4396287/f4beceb7-7463-44a9-be85-22bc59f19f41)

test fail on 2.1.3-rc06

**Comment by w41ter** [comment]
@d378971067 So this result is produced by 2.1.3-rc06?

![image](https://github.com/apache/doris/assets/7908062/03e43575-60c7-43a5-8649-e118f3984fc7)

**Comment by d378971067** [comment]
> @d378971067 So this result is produced by 2.1.3-rc06?
> 
> ![image](https://private-user-images.githubusercontent.com/7908062/329760231-03e43575-60c7-43a5-8649-e118f3984fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTAzMDgsIm5iZiI6MTcxNTQxMDAwOCwicGF0aCI6Ii83OTA4MDYyLzMyOTc2MDIzMS0wM2U0MzU3NS02MGM3LTQzYTUtODY0OS1lMTE4ZjM5ODRmYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDY0NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNjVhMzMxM2ZiOTNhYzRkYjc2MTU0MGI4ODlhMGY1ZTE5YWU2YTdmODE1MGZlNGJmMTliZWI0ZjhiNTI2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHPXAyRm6d4yZ_Y83zdpVI-B_d_ns4m-rrg88_IVMcQ)

yes

**Comment by w41ter** [comment]
@d378971067 It seems that you have encountered a bug in the broker file system. In version 2.1.3, you can use the hdfs repository directly.
