### ISSUE TITLE
[Bug] The ORTHOGONAL_BITMAP_EXPR_CALCULATE_COUNT function result is incorrect

### ISSUE THREAD

**Issue by Jianing-Xu** [apache/doris#36799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.5-rc02

### What's Wrong?

The function **orthogonal_bitmap_expr_calculate_count** calculates the intersection and union of bitmap data incorrectly, and the return value is not fixed
<img width="1148" alt="image" src="https://github.com/apache/doris/assets/38742932/2d4c3e00-0935-4e4b-9e66-d0ee626854b7">
<img width="1308" alt="image" src="https://github.com/apache/doris/assets/38742932/cad9a955-6ce6-461b-9599-bea7f51b9473">
<img width="1344" alt="image" src="https://github.com/apache/doris/assets/38742932/2a9805d1-22f0-434e-afec-f38a61ab4f2c">
<img width="976" alt="image" src="https://github.com/apache/doris/assets/38742932/08bdde5b-a036-43a9-9556-22eb48f9224a">

### What You Expected?

The function returns the correct result

### How to Reproduce?

CREATE TABLE `bitmap_test`
(
    `id` int(11) NOT NULL,
    `tag` int(11) not null ,
    `bitmap` bitmap BITMAP_UNION NOT NULL,
) ENGINE = OLAP AGGREGATE KEY(`id`, `tag`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS AUTO
PROPERTIES (
"replication_allocation" = "tag.location.default: 3"
);

insert into bitmap_test values (1, 1000, bitmap_from_array([1,3,5,7,9]));
insert into bitmap_test values (2, 1000, bitmap_from_array([2,4,6,8,10]));
insert into bitmap_test values (3, 1000, bitmap_from_array([3, 7]));

select id, tag, bitmap_to_array(bitmap) from bitmap_test order by id;
## You need to execute the function orthogonal_bitmap_expr_calculate_count several more times to reproduce it
select orthogonal_bitmap_expr_calculate_count(bitmap, tag, '1000|1000') from bitmap_test;
select orthogonal_bitmap_expr_calculate_count(bitmap, tag, '1000&1000') from bitmap_test;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
this issues have fixed in version 2.0.11, you can upgrade your doris to version 2.0.11
<img width="905" alt="image" src="https://github.com/apache/doris/assets/49646212/3090cb42-2eaf-4d0a-a014-d1ac5a148ec6">

**Comment by Jianing-Xu** [comment]
[1,3,5,7,9],[2,4,6,8,10],[3, 7]
If you're using my sample data, the expected intersection result should be  0 and the expected union result is 10.
The screenshot still do not seem correct.
